version: '3.4'
x-backend:
  &backend
  build: web
  env_file: .env
  depends_on: 
    - redis
  volumes:
    - type: bind
      source: ./web
      target: /usr/src/web 

services:
  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/client
  web:
    << : *backend
    ports: 
      - "8000:8000"
    command: gunicorn -b 0.0.0.0:8000 manage:app
  worker:
    << : *backend
    command: celery -A celeree worker --loglevel=info
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"