version: '3.4'
x-backend:
  &backend
  build: web
  env_file: .env
  links: 
    - redis
  volumes:
    - type: bind
      source: ./web
      target: /usr/src/web 

services:
  client:
    build: client
    volumes:
      - type: bind
        source: ./client
        target: /usr/src/client
    command: npm run build
  web:
    << : *backend
    ports: 
      - "8000:8000"
    command: gunicorn --worker-class gevent --log-level debug -b 0.0.0.0:8000 manage:app
  worker:
    << : *backend
    command: celery -A celeree worker --loglevel=info
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    build: nginx
    ports:
      - "80:80"
    links:
      - web
      - client
    volumes:
      - type: bind
        source: ./client/build
        target: /usr/src/www