defaults: &defaults
  working_directory: ~/cataclysm
  docker:
    - image: circleci/python:3.6.1


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-py-{{ checksum "web/requirements/test.txt" }}-{{ checksum "web/requirements/common.txt" }}
      - run: 
          name: Create or activate virtual environment
          command: bash .circleci/setup-env.sh

      - save_cache:
          key: v3-py-{{ checksum "web/requirements/test.txt" }}-{{ checksum "web/requirements/common.txt" }}
          paths:
            - ~/cataclysm/venv

      - persist_to_workspace:
          root: .
          paths: ./*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/cataclysm
      - run:
          name: Run tests and coverage
          command: |
            ls -al
            . venv/bin/activate
            cd web
            pytest .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/cataclysm
      - add_ssh_keys:
          fingerprints:
            - "9f:72:46:1f:4c:85:11:a6:0f:7f:eb:8a:8d:96:d4:7c"
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            # add management command
            heroku restart --app offline-tube

workflows:
    version: 2
    build_test_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: master
